services:
  postgres:
    image: postgres:latest
    container_name: postgres    
    env_file: .envpostgres
    volumes:
      - '${POSTGRES_STORAGE_PATH}:/var/lib/postgresql/data'
    ports:
      - "5432:5432"