services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file: .envgrafana
    ports:
      - '3000:3000'
    volumes:
      - '${GRAFANA_STORAGE_PATH}:/var/lib/grafana'